backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "Seiten-Inhalt"
    files:
      - file: "content/site.json"
        label: "Startseite (Hero)"
        name: "site"
        fields:
          - { label: "Hero Titel", name: "hero_title", widget: "string" }
          - { label: "Hero Untertitel", name: "hero_subtitle", widget: "text" }
          - { label: "CTA Text", name: "hero_cta", widget: "string" }
